mysql:
  image: mysql:latest
  container_name: HSDock
  ports:
    - "3307:3306"
  volumes:
    - "./hearthstoneBDD.sql:/docker-entrypoint-initdb.d/hearthstoneBDD.sql"
  environment:
    MYSQL_ROOT_PASSWORD: PSHS
    MYSQL_DATABASE: Hearthstone
    MYSQL_USER: User
    MYSQL_PASSWORD: PSUser